from docx import Document
from docx.shared import Cm
import datetime
import argparse
from lxml import etree
try:
    from halo import Halo
except:
    pass

xslt = etree.parse('MML2OMML.XSL')

spgrps = {
    #
    # triclinic
    #
    '1' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<mn>1</mn>'
    '</math>'),
    '2' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<semantics>'
    '<mi>P</mi>'
    '<mover>'
    '<mn>1</mn>'
    '<mo stretchy="false">&#x0305;</mo>'
    '</mover>'
    '</semantics>'
    '</math>'),
    #
    # monoclinic
    #
    '3' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<mn>2</mn>'
    '</math>'),
    '4' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<msub>'
    '<mn>2</mn>'
    '<mn>1</mn>'
    '</msub>'
    '</math>'),
    '5' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>C</mi>'
    '<mn>2</mn>'
    '</math>'),
    '6' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<mn>m</mn>'
    '</math>'),
    '7' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<mn>c</mn>'
    '</math>'),
    '8' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>C</mi>'
    '<mn>m</mn>'
    '</math>'),
    '9' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>C</mi>'
    '<mn>c</mn>'
    '</math>'),
    '10' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<mn>2</mn>'
    '<mn>/</mn>'
    '<mn>m</mn>'
    '</math>'),
    '11' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<msub>'
    '<mn>2</mn>'
    '<mn>1</mn>'
    '</msub>'
    '<mn>/</mn>'
    '<mn>m</mn>'
    '</math>'),
    '12' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>C</mi>'
    '<mn>2</mn>'
    '<mn>/</mn>'
    '<mn>m</mn>'
    '</math>'),
    '13' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<mn>2</mn>'
    '<mn>/</mn>'
    '<mn>c</mn>'
    '</math>'),
    '14' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<msub>'
    '<mn>2</mn>'
    '<mn>1</mn>'
    '</msub>'
    '<mn>/</mn>'
    '<mn>c</mn>'
    '</math>'),
    '15' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>C</mi>'
    '<mn>2</mn>'
    '<mn>/</mn>'
    '<mn>c</mn>'
    '</math>'),
    #
    # orthorombic
    #
    '16' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<mn>2</mn>'
    '<mn>2</mn>'
    '<mn>2</mn>'
    '</math>'
    ),
    '17' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<mn>2</mn>'
    '<mn>2</mn>'
    '<msub>'
    '<mn>2</mn>'
    '<mn>1</mn>'
    '</msub>'
    '</math>'
    ),
    '18' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<msub>'
    '<mn>2</mn>'
    '<mn>1</mn>'
    '</msub>'
    '<msub>'
    '<mn>2</mn>'
    '<mn>1</mn>'
    '</msub>'
    '<mn>2</mn>'
    '</math>'
    ),
    '19' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<msub>'
    '<mn>2</mn>'
    '<mn>1</mn>'
    '</msub>'
    '<msub>'
    '<mn>2</mn>'
    '<mn>1</mn>'
    '</msub>'
    '<msub>'
    '<mn>2</mn>'
    '<mn>1</mn>'
    '</msub>'
    '</math>'
    ),
    '20' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>C</mi>'
    '<mn>2</mn>'
    '<mn>2</mn>'
    '<msub>'
    '<mn>2</mn>'
    '<mn>1</mn>'
    '</msub>'
    '</math>'
    ),
    '21' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>C</mi>'
    '<mn>2</mn>'
    '<mn>2</mn>'
    '<mn>2</mn>'
    '</math>'
    ),
    '22' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>F</mi>'
    '<mn>2</mn>'
    '<mn>2</mn>'
    '<mn>2</mn>'
    '</math>'
    ),
    '23' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>I</mi>'
    '<mn>2</mn>'
    '<mn>2</mn>'
    '<mn>2</mn>'
    '</math>'
    ),
    '24' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>I</mi>'
    '<msub>'
    '<mn>2</mn>'
    '<mn>1</mn>'
    '</msub>'
    '<msub>'
    '<mn>2</mn>'
    '<mn>1</mn>'
    '</msub>'
    '<msub>'
    '<mn>2</mn>'
    '<mn>1</mn>'
    '</msub>'
    '</math>'
    ),
    '25' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<mn>m</mn>'
    '<mn>m</mn>'
    '<mn>2</mn>'
    '</math>'
    ),
    '26' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<mn>m</mn>'
    '<mn>c</mn>'
    '<msub>'
    '<mn>2</mn>'
    '<mn>1</mn>'
    '</msub>'
    '</math>'
    ),
    '27' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<mn>c</mn>'
    '<mn>c</mn>'
    '<mn>2</mn>'
    '</math>'
    ),
    '28' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<mn>m</mn>'
    '<mn>a</mn>'
    '<mn>2</mn>'
    '</math>'
    ),
    '29' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<mn>c</mn>'
    '<mn>a</mn>'
    '<msub>'
    '<mn>2</mn>'
    '<mn>1</mn>'
    '</msub>'
    '</math>'
    ),
    '30' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<mn>n</mn>'
    '<mn>c</mn>'
    '<mn>2</mn>'
    '</math>'
    ),
    '31' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<mn>m</mn>'
    '<mn>n</mn>'
    '<msub>'
    '<mn>2</mn>'
    '<mn>1</mn>'
    '</msub>'
    '</math>'
    ),
    '32' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<mn>b</mn>'
    '<mn>a</mn>'
    '<mn>2</mn>'
    '</math>'),
    '33' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<mn>n</mn>'
    '<mn>a</mn>'
    '<msub>'
    '<mn>2</mn>'
    '<mn>1</mn>'
    '</msub>'
    '</math>'
    ),
    '34' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<mn>n</mn>'
    '<mn>n</mn>'
    '<mn>2</mn>'
    '</math>'),
    '35' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>C</mi>'
    '<mn>m</mn>'
    '<mn>m</mn>'
    '<mn>2</mn>'
    '</math>'),
    '36' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>C</mi>'
    '<mn>m</mn>'
    '<mn>c</mn>'
    '<msub>'
    '<mn>2</mn>'
    '<mn>1</mn>'
    '</msub>'
    '</math>'
    ),
    '37' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>C</mi>'
    '<mn>c</mn>'
    '<mn>c</mn>'
    '<mn>2</mn>'
    '</math>'), 
    '38' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>A</mi>'
    '<mn>m</mn>'
    '<mn>m</mn>'
    '<mn>2</mn>'
    '</math>'),
    '39' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>A</mi>'
    '<mn>e</mn>'
    '<mn>m</mn>'
    '<mn>2</mn>'
    '</math>'),
    '40' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>A</mi>'
    '<mn>m</mn>'
    '<mn>a</mn>'
    '<mn>2</mn>'
    '</math>'),
    '41' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>A</mi>'
    '<mn>e</mn>'
    '<mn>a</mn>'
    '<mn>2</mn>'
    '</math>'),
    '42' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>F</mi>'
    '<mn>m</mn>'
    '<mn>m</mn>'
    '<mn>2</mn>'
    '</math>'),
    '43' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>F</mi>'
    '<mn>d</mn>'
    '<mn>d</mn>'
    '<mn>2</mn>'
    '</math>'),
    '44' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>I</mi>'
    '<mn>m</mn>'
    '<mn>m</mn>'
    '<mn>2</mn>'
    '</math>'),
    '45' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>I</mi>'
    '<mn>b</mn>'
    '<mn>a</mn>'
    '<mn>2</mn>'
    '</math>'),
    '46' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>I</mi>'
    '<mn>m</mn>'
    '<mn>a</mn>'
    '<mn>2</mn>'
    '</math>'),
    '47' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<mn>m</mn>'
    '<mn>m</mn>'
    '<mn>m</mn>'
    '</math>'),
    '48' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<mn>n</mn>'
    '<mn>n</mn>'
    '<mn>n</mn>'
    '</math>'),
    '49' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<mn>c</mn>'
    '<mn>c</mn>'
    '<mn>m</mn>'
    '</math>'),
    '50' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<mn>b</mn>'
    '<mn>a</mn>'
    '<mn>n</mn>'
    '</math>'),
    '51' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<mn>m</mn>'
    '<mn>m</mn>'
    '<mn>a</mn>'
    '</math>'),
    '52' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<mn>n</mn>'
    '<mn>n</mn>'
    '<mn>a</mn>'
    '</math>'),
    '53' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<mn>m</mn>'
    '<mn>n</mn>'
    '<mn>a</mn>'
    '</math>'),
    '54' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<mn>c</mn>'
    '<mn>c</mn>'
    '<mn>a</mn>'
    '</math>'),
    '55' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<mn>b</mn>'
    '<mn>a</mn>'
    '<mn>m</mn>'
    '</math>'),
    '56' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<mn>c</mn>'
    '<mn>c</mn>'
    '<mn>n</mn>'
    '</math>'),
    '57' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<mn>b</mn>'
    '<mn>c</mn>'
    '<mn>m</mn>'
    '</math>'),
    '58' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<mn>n</mn>'
    '<mn>n</mn>'
    '<mn>m</mn>'
    '</math>'),
    '59' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<mn>m</mn>'
    '<mn>m</mn>'
    '<mn>n</mn>'
    '</math>'),
    '60' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<mn>b</mn>'
    '<mn>c</mn>'
    '<mn>n</mn>'
    '</math>'),
    '61' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<mn>b</mn>'
    '<mn>c</mn>'
    '<mn>a</mn>'
    '</math>'),
    '62' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<mn>n</mn>'
    '<mn>m</mn>'
    '<mn>a</mn>'
    '</math>'),
    '63' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>C</mi>'
    '<mn>m</mn>'
    '<mn>c</mn>'
    '<mn>m</mn>'
    '</math>'),
    '64' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>C</mi>'
    '<mn>m</mn>'
    '<mn>c</mn>'
    '<mn>a</mn>'
    '</math>'),
    '65' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>C</mi>'
    '<mn>m</mn>'
    '<mn>m</mn>'
    '<mn>m</mn>'
    '</math>'),
    '66' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>C</mi>'
    '<mn>c</mn>'
    '<mn>c</mn>'
    '<mn>m</mn>'
    '</math>'),
    '67' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>C</mi>'
    '<mn>m</mn>'
    '<mn>m</mn>'
    '<mn>e</mn>'
    '</math>'),
    '68' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>C</mi>'
    '<mn>c</mn>'
    '<mn>c</mn>'
    '<mn>e</mn>'
    '</math>'),
    '69' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>F</mi>'
    '<mn>m</mn>'
    '<mn>m</mn>'
    '<mn>m</mn>'
    '</math>'),
    '70' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>F</mi>'
    '<mn>d</mn>'
    '<mn>d</mn>'
    '<mn>d</mn>'
    '</math>'),
    '71' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>I</mi>'
    '<mn>m</mn>'
    '<mn>m</mn>'
    '<mn>m</mn>'
    '</math>'),
    '72' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>I</mi>'
    '<mn>b</mn>'
    '<mn>a</mn>'
    '<mn>m</mn>'
    '</math>'),
    '73' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>I</mi>'
    '<mn>b</mn>'
    '<mn>c</mn>'
    '<mn>a</mn>'
    '</math>'),
    '74' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>I</mi>'
    '<mn>m</mn>'
    '<mn>m</mn>'
    '<mn>a</mn>'
    '</math>'),
    #
    # tetragonal
    #
    '75' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<mn>4</mn>'
    '</math>'),
    '76' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<msub>'
    '<mn>4</mn>'
    '<mn>1</mn>'
    '</msub>'
    '</math>'),
    '77' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<msub>'
    '<mn>4</mn>'
    '<mn>2</mn>'
    '</msub>'
    '</math>'),
    '78' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<msub>'
    '<mn>4</mn>'
    '<mn>3</mn>'
    '</msub>'
    '</math>'),
    '79' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>I</mi>'
    '<mn>4</mn>'
    '</math>'),
    '80' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>I</mi>'
    '<msub>'
    '<mn>4</mn>'
    '<mn>1</mn>'
    '</msub>'
    '</math>'),
    '81' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<mover accent="true">_<mn>4</mn></mover>'
    '</math>'),
    '82' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>I</mi>'
    '<mover accent="true">_<mn>4</mn></mover>'
    '</math>'),
    '83' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<mn>4</mn>'
    '<mn>/</mn>'
    '<mn>m</mn>'
    '</math>'),
    '84' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<msub>'
    '<mn>4</mn>'
    '<mn>2</mn>'
    '</msub>'
    '<mn>/</mn>'
    '<mn>m</mn>'
    '</math>'),
    '85' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<mn>4</mn>'
    '<mn>/</mn>'
    '<mn>n</mn>'
    '</math>'),
    '86' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<msub>'
    '<mn>4</mn>'
    '<mn>2</mn>'
    '</msub>'
    '<mn>/</mn>'
    '<mn>n</mn>'
    '</math>'),
    '87' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>I</mi>'
    '<mn>4</mn>'
    '<mn>/</mn>'
    '<mn>m</mn>'
    '</math>'),
    '88' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>I</mi>'
    '<msub>'
    '<mn>4</mn>'
    '<mn>1</mn>'
    '</msub>'
    '<mn>/</mn>'
    '<mn>a</mn>'
    '</math>'),
    '89' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<mn>4</mn>'
    '<mn>2</mn>'
    '<mn>2</mn>'
    '</math>'),
    '90' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<mn>4</mn>'
    '<msub>'
    '<mn>2</mn>'
    '<mn>1</mn>'
    '</msub>'
    '<mn>2</mn>'
    '</math>'),
    '91' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<msub>'
    '<mn>4</mn>'
    '<mn>1</mn>'
    '</msub>'
    '<mn>2</mn>'
    '<mn>2</mn>'
    '</math>'),
    '92' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<msub>'
    '<mn>4</mn>'
    '<mn>1</mn>'
    '</msub>'
    '<msub>'
    '<mn>2</mn>'
    '<mn>1</mn>'
    '</msub>'
    '<mn>2</mn>'
    '</math>'),
    '93' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<msub>'
    '<mn>4</mn>'
    '<mn>2</mn>'
    '</msub>'
    '<mn>2</mn>'
    '<mn>2</mn>'
    '</math>'),
    '94' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<msub>'
    '<mn>4</mn>'
    '<mn>2</mn>'
    '</msub>'
    '<msub>'
    '<mn>2</mn>'
    '<mn>1</mn>'
    '</msub>'
    '<mn>2</mn>'
    '</math>'),
    '95' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<msub>'
    '<mn>4</mn>'
    '<mn>3</mn>'
    '</msub>'
    '<mn>2</mn>'
    '<mn>2</mn>'
    '</math>'),
    '96' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<msub>'
    '<mn>4</mn>'
    '<mn>3</mn>'
    '</msub>'
    '<msub>'
    '<mn>2</mn>'
    '<mn>1</mn>'
    '</msub>'
    '<mn>2</mn>'
    '</math>'),
    '97' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>I</mi>'
    '<mn>4</mn>'
    '<mn>2</mn>'
    '<mn>2</mn>'
    '</math>'),
    '98' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>I</mi>'
    '<msub>'
    '<mn>4</mn>'
    '<mn>1</mn>'
    '</msub>'
    '<mn>2</mn>'
    '<mn>2</mn>'
    '</math>'),
    '99' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<mn>4</mn>'
    '<mn>m</mn>'
    '<mn>m</mn>'
    '</math>'),
    '100' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<mn>4</mn>'
    '<mn>b</mn>'
    '<mn>m</mn>'
    '</math>'),
    '101' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<msub>'
    '<mn>4</mn>'
    '<mn>2</mn>'
    '</msub>'
    '<mn>c</mn>'
    '<mn>m</mn>'
    '</math>'),
    '102' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<msub>'
    '<mn>4</mn>'
    '<mn>2</mn>'
    '</msub>'
    '<mn>n</mn>'
    '<mn>m</mn>'
    '</math>'),
    '103' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<mn>4</mn>'
    '<mn>c</mn>'
    '<mn>c</mn>'),
    '104' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<mn>4</mn>'
    '<mn>n</mn>'
    '<mn>c</mn>'
    '</math>'),
    '105' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<msub>'
    '<mn>4</mn>'
    '<mn>2</mn>'
    '</msub>'
    '<mn>m</mn>'
    '<mn>c</mn>'
    '</math>'),
    '106' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<msub>'
    '<mn>4</mn>'
    '<mn>2</mn>'
    '</msub>'
    '<mn>b</mn>'
    '<mn>c</mn>'
    '</math>'),
    '107' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>I</mi>'
    '<mn>4</mn>'
    '<mn>m</mn>'
    '<mn>m</mn>'
    '</math>'),
    '108' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>I</mi>'
    '<mn>4</mn>'
    '<mn>c</mn>'
    '<mn>m</mn>'
    '</math>'),
    '109' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>I</mi>'
    '<msub>'
    '<mn>4</mn>'
    '<mn>1</mn>'
    '</msub>'
    '<mn>m</mn>'
    '<mn>d</mn>'
    '</math>'),
    '110' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>I</mi>'
    '<msub>'
    '<mn>4</mn>'
    '<mn>2</mn>'
    '</msub>'
    '<mn>c</mn>'
    '<mn>d</mn>'
    '</math>'),
    '111' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<mover accent="true">'
    '<mn>4</mn>'
    '<mn>-</mn>'
    '</mover>'
    '<mn>2</mn>'
    '<mn>m</mn>'
    '</math>'),
    '112' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<mover accent="true">'
    '<mn>4</mn>'
    '<mn>-</mn>'
    '</mover>'
    '<mn>2</mn>'
    '<mn>c</mn>'
    '</math>'),
    '113' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<mover accent="true">'
    '<mn>4</mn>'
    '<mn>-</mn>'
    '</mover>'
    '<msub>'
    '<mn>2</mn>'
    '<mn>1</mn>'
    '</msub>'
    '<mn>m</mn>'
    '</math>'),
    '114' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<mover accent="true">'
    '<mn>4</mn>'
    '<mn>-</mn>'
    '</mover>'
    '<msub>'
    '<mn>2</mn>'
    '<mn>1</mn>'
    '</msub>'
    '<mn>c</mn>'
    '</math>'),
    '115' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<mover accent="true">'
    '<mn>4</mn>'
    '<mn>-</mn>'
    '</mover>'
    '<mn>m</mn>'
    '<mn>2</mn>'
    '</math>'),
    '116' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<mover accent="true">'
    '<mn>4</mn>'
    '<mn>-</mn>'
    '</mover>'
    '<mn>c</mn>'
    '<mn>2</mn>'
    '</math>'),
    '117' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<mover accent="true">'
    '<mn>4</mn>'
    '<mn>-</mn>'
    '</mover>'
    '<mn>b</mn>'
    '<mn>2</mn>'
    '</math>'),
    '118' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<mover accent="true">'
    '<mn>4</mn>'
    '<mn>-</mn>'
    '</mover>'
    '<mn>n</mn>'
    '<mn>2</mn>'
    '</math>'),
    '119' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>I</mi>'
    '<mover accent="true">'
    '<mn>4</mn>'
    '<mn>-</mn>'
    '</mover>'
    '<mn>m</mn>'
    '<mn>2</mn>'
    '</math>'),
    '120' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>I</mi>'
    '<mover accent="true">'
    '<mn>4</mn>'
    '<mn>-</mn>'
    '</mover>'
    '<mn>c</mn>'
    '<mn>2</mn>'
    '</math>'),
    '121' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>I</mi>'
    '<mover accent="true">'
    '<mn>4</mn>'
    '<mn>-</mn>'
    '</mover>'
    '<mn>2</mn>'
    '<mn>m</mn>'
    '</math>'),
    '122' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>I</mi>'
    '<mover accent="true">'
    '<mn>4</mn>'
    '<mn>-</mn>'
    '</mover>'
    '<mn>2</mn>'
    '<mn>d</mn>'
    '</math>'),
    '123' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<mn>4</mn>'
    '<mn>/</mn>'
    '<mn>m</mn>'
    '<mn>m</mn>'
    '<mn>m</mn>'
    '</math>'),
    '124' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<mn>4</mn>'
    '<mn>/</mn>'
    '<mn>m</mn>'
    '<mn>c</mn>'
    '<mn>c</mn>'
    '</math>'),
    '125' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<mn>4</mn>'
    '<mn>/</mn>'
    '<mn>n</mn>'
    '<mn>b</mn>'
    '<mn>m</mn>'
    '</math>'),
    '126' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<mn>4</mn>'
    '<mn>/</mn>'
    '<mn>n</mn>'
    '<mn>n</mn>'
    '<mn>c</mn>'
    '</math>'),
    '127' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<mn>4</mn>'
    '<mn>/</mn>'
    '<mn>m</mn>'
    '<mn>b</mn>'
    '<mn>m</mn>'
    '</math>'),
    '128' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<mn>4</mn>'
    '<mn>/</mn>'
    '<mn>m</mn>'
    '<mn>n</mn>'
    '<mn>c</mn>'
    '</math>'),
    '129' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<mn>4</mn>'
    '<mn>/</mn>'
    '<mn>n</mn>'
    '<mn>m</mn>'
    '<mn>m</mn>'
    '</math>'),
    '130' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<mn>4</mn>'
    '<mn>/</mn>'
    '<mn>n</mn>'
    '<mn>c</mn>'
    '<mn>c</mn>'
    '</math>'),
    '131' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<msub>'
    '<mn>4</mn>'
    '<mn>2</mn>'
    '</msub>'
    '<mn>/</mn>'
    '<mn>m</mn>'
    '<mn>m</mn>'
    '<mn>c</mn>'
    '</math>'),
    '132' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<msub>'
    '<mn>4</mn>'
    '<mn>2</mn>'
    '</msub>'
    '<mn>/</mn>'
    '<mn>m</mn>'
    '<mn>c</mn>'
    '<mn>m</mn>'
    '</math>'),
    '133' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<msub>'
    '<mn>4</mn>'
    '<mn>2</mn>'
    '</msub>'
    '<mn>/</mn>'
    '<mn>n</mn>'
    '<mn>b</mn>'
    '<mn>c</mn>'
    '</math>'),
    '134' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<msub>'
    '<mn>4</mn>'
    '<mn>2</mn>'
    '</msub>'
    '<mn>/</mn>'
    '<mn>n</mn>'
    '<mn>n</mn>'
    '<mn>m</mn>'
    '</math>'),
    '135' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<msub>'
    '<mn>4</mn>'
    '<mn>2</mn>'
    '</msub>'
    '<mn>/</mn>'
    '<mn>m</mn>'
    '<mn>b</mn>'
    '<mn>c</mn>'
    '</math>'),
    '136' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<msub>'
    '<mn>4</mn>'
    '<mn>2</mn>'
    '</msub>'
    '<mn>/</mn>'
    '<mn>m</mn>'
    '<mn>n</mn>'
    '<mn>m</mn>'
    '</math>'),
    '137' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<msub>'
    '<mn>4</mn>'
    '<mn>2</mn>'
    '</msub>'
    '<mn>/</mn>'
    '<mn>n</mn>'
    '<mn>m</mn>'
    '<mn>c</mn>'
    '</math>'),
    '138' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<msub>'
    '<mn>4</mn>'
    '<mn>2</mn>'
    '</msub>'
    '<mn>/</mn>'
    '<mn>n</mn>'
    '<mn>c</mn>'
    '<mn>m</mn>'
    '</math>'),
    '139' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>I</mi>'
    '<mn>4</mn>'
    '<mn>/</mn>'
    '<mn>m</mn>'
    '<mn>m</mn>'
    '<mn>m</mn>'
    '</math>'),
    '140' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>I</mi>'
    '<mn>4</mn>'
    '<mn>/</mn>'
    '<mn>m</mn>'
    '<mn>c</mn>'
    '<mn>m</mn>'
    '</math>'),
    '141' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>I</mi>'
    '<msub>'
    '<mn>4</mn>'
    '<mn>1</mn>'
    '</msub>'
    '<mn>/</mn>'
    '<mn>a</mn>'
    '<mn>m</mn>'
    '<mn>d</mn>'
    '</math>'),
    '142' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>I</mi>'
    '<msub>'
    '<mn>4</mn>'
    '<mn>1</mn>'
    '</msub>'
    '<mn>/</mn>'
    '<mn>a</mn>'
    '<mn>c</mn>'
    '<mn>d</mn>'
    '</math>'),
    #
    # trigonal
    #
    '143' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<mn>3</mn>'
    '</math>'),
    '144' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<msub>'
    '<mn>3</mn>'
    '<mn>1</mn>'
    '</msub>'
    '</math>'),
    '145' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<msub>'
    '<mn>3</mn>'
    '<mn>3</mn>'
    '</msub>'
    '</math>'),
    '146' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>R</mi>'
    '<mn>3</mn>'
    '</math>'),
    '147' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<mover accent="true"'
    '<mn>3</mn>'
    '<mn>-</mn>'
    '</mover>'
    '</math>'),
    '148' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>R</mi>'
    '<mover accent="true"'
    '<mn>3</mn>'
    '<mn>-</mn>'
    '</mover>'
    '</math>'),
    '149' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<mn>3</mn>'
    '<mn>1</mn>'
    '<mn>2</mn>'
    '</math>'),
    '150' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<mn>3</mn>'
    '<mn>2</mn>'
    '<mn>1</mn>'
    '</math>'),
    '151' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<mover accent="true"'
    '<mn>3</mn>'
    '<mn>1</mn>'
    '</mover>'
    '<mn>1</mn>'
    '<mn>2</mn>'
    '</math>'),
    '152' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<mover accent="true"'
    '<mn>3</mn>'
    '<mn>1</mn>'
    '</mover>'
    '<mn>2</mn>'
    '<mn>1</mn>'
    '</math>'),
    '153' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<mover accent="true"'
    '<mn>3</mn>'
    '<mn>2</mn>'
    '</mover>'
    '<mn>1</mn>'
    '<mn>2</mn>'
    '</math>'),
    '154' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<mover accent="true"'
    '<mn>3</mn>'
    '<mn>2</mn>'
    '</mover>'
    '<mn>2</mn>'
    '<mn>1</mn>'
    '</math>'),
    '155' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>R</mi>'
    '<mn>3</mn>'
    '<mn>2</mn>'
    '</math>'),
    '156' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<mn>3</mn>'
    '<mn>m</mn>'
    '<mn>1</mn>'
    '</math>'),
    '157' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<mn>3</mn>'
    '<mn>1</mn>'
    '<mn>m</mn>'
    '</math>'),
    '158' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<mn>3</mn>'
    '<mn>c</mn>'
    '<mn>1</mn>'
    '</math>'),
    '159' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<mn>3</mn>'
    '<mn>1</mn>'
    '<mn>c</mn>'
    '</math>'),
    '160' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>R</mi>'
    '<mn>3</mn>'
    '<mn>m</mn>'
    '</math>'),
    '161' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>R</mi>'
    '<mn>3</mn>'
    '<mn>c</mn>'
    '</math>'),
    '162' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<mover accent="true">'
    '<mn>3</mn>'
    '<mn>-</mn>'
    '<mn>1</mn>'
    '<mn>m</mn>'
    '</math>'),
    '163' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<mover accent="true">'
    '<mn>3</mn>'
    '<mn>-</mn>'
    '<mn>1</mn>'
    '<mn>c</mn>'
    '</math>'),
    '164' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<mover accent="true">'
    '<mn>3</mn>'
    '<mn>-</mn>'
    '<mn>m</mn>'
    '<mn>1</mn>'
    '</math>'),
    '165' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<mover accent="true">'
    '<mn>3</mn>'
    '<mn>-</mn>'
    '<mn>c</mn>'
    '<mn>1</mn>'
    '</math>'),
    '166' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>R</mi>'
    '<mover accent="true">'
    '<mn>3</mn>'
    '<mn>-</mn>'
    '<mn>m</mn>'
    '</math>'),
    '167' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>R</mi>'
    '<mover accent="true">'
    '<mn>3</mn>'
    '<mn>-</mn>'
    '<mn>c</mn>'
    '</math>'),
    #
    # hexagonal
    #
    '168' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<mn>6</mn>'
    '</math>'),
    '169' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<msub>'
    '<mn>6</mn>'
    '<mn>1</mn>'
    '</msub>'    
    '</math>'),
    '170' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<msub>'
    '<mn>6</mn>'
    '<mn>5</mn>'
    '</msub>'    
    '</math>'),
    '171' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<msub>'
    '<mn>6</mn>'
    '<mn>2</mn>'
    '</msub>'    
    '</math>'),
    '172' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<msub>'
    '<mn>6</mn>'
    '<mn>4</mn>'
    '</msub>'    
    '</math>'),
    '173' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<msub>'
    '<mn>6</mn>'
    '<mn>3</mn>'
    '</msub>'    
    '</math>'),
    '174' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<mover accent="true">'
    '<mn>6</mn>'
    '<mn>-</mn>'
    '</mover>'    
    '</math>'),
    '175' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<mn>6</mn>'
    '<mn>/</mn>'
    '<mn>m</mn>'
    '</math>'),
    '176' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<msub>'
    '<mn>6</mn>'
    '<mn>3</mn>'
    '</msub>'
    '<mn>/</mn>'
    '<mn>m</mn>'
    '</math>'),
    '177' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<mn>6</mn>'
    '<mn>2</mn>'
    '<mn>2</mn>'
    '</math>'),
    '178' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<msub>'
    '<mn>6</mn>'
    '<mn>1</mn>'
    '</msub>'
    '<mn>2</mn>'
    '<mn>2</mn>'
    '</math>'),
    '179' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<msub>'
    '<mn>6</mn>'
    '<mn>5</mn>'
    '</msub>'
    '<mn>2</mn>'
    '<mn>2</mn>'
    '</math>'),
    '180' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<msub>'
    '<mn>6</mn>'
    '<mn>2</mn>'
    '</msub>'
    '<mn>2</mn>'
    '<mn>2</mn>'
    '</math>'),
    '181' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<msub>'
    '<mn>6</mn>'
    '<mn>4</mn>'
    '</msub>'
    '<mn>2</mn>'
    '<mn>2</mn>'
    '</math>'),
    '182' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<msub>'
    '<mn>6</mn>'
    '<mn>3</mn>'
    '</msub>'
    '<mn>2</mn>'
    '<mn>2</mn>'
    '</math>'),
    '183' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<mn>6</mn>'
    '<mn>m</mn>'
    '<mn>m</mn>'
    '</math>'),
    '184' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<mn>6</mn>'
    '<mn>c</mn>'
    '<mn>c</mn>'
    '</math>'),
    '185' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<msub>'
    '<mn>6</mn>'
    '<mn>3</mn>'
    '</msub>'
    '<mn>c</mn>'
    '<mn>m</mn>'
    '</math>'),
    '186' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<msub>'
    '<mn>6</mn>'
    '<mn>3</mn>'
    '</msub>'
    '<mn>m</mn>'
    '<mn>c</mn>'
    '</math>'),
    '187' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<mover accent="true">'
    '<mn>6</mn>'
    '<mn>-</mn>'
    '</mover>'
    '<mn>m</mn>'
    '<mn>2</mn>'
    '</math>'),
    '188' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<mover accent="true">'
    '<mn>6</mn>'
    '<mn>-</mn>'
    '</mover>'
    '<mn>c</mn>'
    '<mn>2</mn>'
    '</math>'),
    '189' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<mover accent="true">'
    '<mn>6</mn>'
    '<mn>-</mn>'
    '</mover>'
    '<mn>2</mn>'
    '<mn>m</mn>'
    '</math>'),
    '190' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<mover accent="true">'
    '<mn>6</mn>'
    '<mn>-</mn>'
    '</mover>'
    '<mn>2</mn>'
    '<mn>c</mn>'
    '</math>'),
    '191' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<mn>6</mn>'
    '<mn>/</mn>'
    '<mn>m</mn>'
    '<mn>m</mn>'
    '<mn>m</mn>'
    '</math>'),
    '192' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<mn>6</mn>'
    '<mn>/</mn>'
    '<mn>m</mn>'
    '<mn>c</mn>'
    '<mn>c</mn>'
    '</math>'),
    '193' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<mn>6</mn>'
    '<mn>/</mn>'
    '<mn>m</mn>'
    '<mn>c</mn>'
    '<mn>m</mn>'
    '</math>'),
    '194' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<mn>6</mn>'
    '<mn>/</mn>'
    '<mn>m</mn>'
    '<mn>m</mn>'
    '<mn>c</mn>'
    '</math>'),
    #
    # cubic
    #
    '195' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<mn>2</mn>'
    '<mn>3</mn>'
    '</math>'),
    '196' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>F</mi>'
    '<mn>2</mn>'
    '<mn>3</mn>'
    '</math>'),
    '197' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>I</mi>'
    '<mn>2</mn>'
    '<mn>3</mn>'
    '</math>'),
    '198' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<msub>'
    '<mn>2</mn>'
    '<mn>1</mn>'
    '</msub>'
    '<mn>3</mn>'
    '</math>'),
    '199' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>I</mi>'
    '<msub>'
    '<mn>2</mn>'
    '<mn>1</mn>'
    '</msub>'
    '<mn>3</mn>'
    '</math>'),
    '200' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<mn>m</mn>'
    '<mover accent="true">'
    '<mn>3</mn>'
    '<mn>-</mn>'
    '</mover>'
    '</math>'),
    '201' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<mn>n</mn>'
    '<mover accent="true">'
    '<mn>3</mn>'
    '<mn>-</mn>'
    '</mover>'
    '</math>'),
    '202' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>F</mi>'
    '<mn>m</mn>'
    '<mover accent="true">'
    '<mn>3</mn>'
    '<mn>-</mn>'
    '</mover>'
    '</math>'),
    '203' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>F</mi>'
    '<mn>d</mn>'
    '<mover accent="true">'
    '<mn>3</mn>'
    '<mn>-</mn>'
    '</mover>'
    '</math>'),
    '204' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>I</mi>'
    '<mn>m</mn>'
    '<mover accent="true">'
    '<mn>3</mn>'
    '<mn>-</mn>'
    '</mover>'
    '</math>'),
    '205' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<mn>a</mn>'
    '<mover accent="true">'
    '<mn>3</mn>'
    '<mn>-</mn>'
    '</mover>'
    '</math>'),
    '206' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>I</mi>'
    '<mn>a</mn>'
    '<mover accent="true">'
    '<mn>3</mn>'
    '<mn>-</mn>'
    '</mover>'
    '</math>'),
    '207' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<mn>4</mn>'
    '<mn>3</mn>'
    '<mn>2</mn>'
    '</math>'),
    '208' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<msub>'
    '<mn>4</mn>'
    '<mn>2</mn>'
    '</msub>'
    '<mn>3</mn>'
    '<mn>2</mn>'
    '</math>'),
    '209' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>F</mi>'
    '<mn>4</mn>'
    '<mn>3</mn>'
    '<mn>2</mn>'
    '</math>'),
    '210' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>F</mi>'
    '<msub>'
    '<mn>4</mn>'
    '<mn>1</mn>'
    '</msub>'
    '<mn>3</mn>'
    '<mn>2</mn>'
    '</math>'),
    '211' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>I</mi>'
    '<mn>4</mn>'
    '<mn>3</mn>'
    '<mn>2</mn>'
    '</math>'),
    '212' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<msub>'
    '<mn>4</mn>'
    '<mn>3</mn>'
    '</msub>'
    '<mn>3</mn>'
    '<mn>2</mn>'
    '</math>'),
    '213' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<msub>'
    '<mn>4</mn>'
    '<mn>1</mn>'
    '</msub>'
    '<mn>3</mn>'
    '<mn>2</mn>'
    '</math>'),
    '214' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>I</mi>'
    '<msub>'
    '<mn>4</mn>'
    '<mn>1</mn>'
    '</msub>'
    '<mn>3</mn>'
    '<mn>2</mn>'
    '</math>'),
    '215' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<mover accent="true">'
    '<mn>4</mn>'
    '<mn>-</mn>'
    '</mover>'
    '<mn>3</mn>'
    '<mn>m</mn>'
    '</math>'),
    '216' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>F</mi>'
    '<mover accent="true">'
    '<mn>4</mn>'
    '<mn>-</mn>'
    '</mover>'
    '<mn>3</mn>'
    '<mn>m</mn>'
    '</math>'),
    '217' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>I</mi>'
    '<mover accent="true">'
    '<mn>4</mn>'
    '<mn>-</mn>'
    '</mover>'
    '<mn>3</mn>'
    '<mn>m</mn>'
    '</math>'),
    '218' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<mover accent="true">'
    '<mn>4</mn>'
    '<mn>-</mn>'
    '</mover>'
    '<mn>3</mn>'
    '<mn>n</mn>'
    '</math>'),
    '219' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>F</mi>'
    '<mover accent="true">'
    '<mn>4</mn>'
    '<mn>-</mn>'
    '</mover>'
    '<mn>3</mn>'
    '<mn>c</mn>'
    '</math>'),
    '220' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>I</mi>'
    '<mover accent="true">'
    '<mn>4</mn>'
    '<mn>-</mn>'
    '</mover>'
    '<mn>3</mn>'
    '<mn>d</mn>'
    '</math>'),
    '221' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<mn>m</mn>'
    '<mover accent="true">'
    '<mn>3</mn>'
    '<mn>-</mn>'
    '</mover>'
    '<mn>m</mn>'
    '</math>'),
    '222' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<mn>n</mn>'
    '<mover accent="true">'
    '<mn>3</mn>'
    '<mn>-</mn>'
    '</mover>'
    '<mn>n</mn>'
    '</math>'),
    '223' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<mn>m</mn>'
    '<mover accent="true">'
    '<mn>3</mn>'
    '<mn>-</mn>'
    '</mover>'
    '<mn>n</mn>'
    '</math>'),
    '224' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>P</mi>'
    '<mn>n</mn>'
    '<mover accent="true">'
    '<mn>3</mn>'
    '<mn>-</mn>'
    '</mover>'
    '<mn>m</mn>'
    '</math>'),
    '225' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>F</mi>'
    '<mn>m</mn>'
    '<mover accent="true">'
    '<mn>3</mn>'
    '<mn>-</mn>'
    '</mover>'
    '<mn>m</mn>'
    '</math>'),
    '226' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>F</mi>'
    '<mn>m</mn>'
    '<mover accent="true">'
    '<mn>3</mn>'
    '<mn>-</mn>'
    '</mover>'
    '<mn>c</mn>'
    '</math>'),
    '227' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>F</mi>'
    '<mn>d</mn>'
    '<mover accent="true">'
    '<mn>3</mn>'
    '<mn>-</mn>'
    '</mover>'
    '<mn>m</mn>'
    '</math>'),
    '228' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>F</mi>'
    '<mn>d</mn>'
    '<mover accent="true">'
    '<mn>3</mn>'
    '<mn>-</mn>'
    '</mover>'
    '<mn>c</mn>'
    '</math>'),
    '229' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>I</mi>'
    '<mn>m</mn>'
    '<mover accent="true">'
    '<mn>3</mn>'
    '<mn>-</mn>'
    '</mover>'
    '<mn>m</mn>'
    '</math>'),
    '230' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
    '<mi>I</mi>'
    '<mn>a</mn>'
    '<mover accent="true">'
    '<mn>3</mn>'
    '<mn>-</mn>'
    '</mover>'
    '<mn>d</mn>'
    '</math>'),
}

parser = argparse.ArgumentParser(description='Generate pretty Strucutre Reports.')
parser.add_argument('-u','--user', help='name of the synthetic chemist' )
parser.add_argument('-i','--input', help='name of input CIF-file' )
parser.add_argument('-s','--special', help='special details for the refinement' )
parser.add_argument('-d','--docx', help='path to the template docx file' )

now = datetime.datetime.now()

keys_report = ['ID', 'USER', 'DATE', 'SUM', 'SUM1', 'MOI', 'WEIGHT', 'CRYSSYSTEM', 'SPGRP', 'CELLA', 'CELLB',
    'CELLC', 'ALPHA', 'BETA', 'GAMMA', 'VOLUME', 'ZERR', 'DENSITY', 'MU', 'COMPLETENESS', 'THETAMIN',
    'THETAMAX', 'COLLRFL', 'UNIQUE', 'SOMETHING', 'ABSCORR', 'TMAX', 'TMIN', 'DATA', 'PARAM', 'RESTR', 'GOOF',
    'R1ALL', 'R12SIG', 'WR2ALL', 'WR2SIG', 'HIGHPEAK', 'DEEPHOLE', 'SIZEMAX', 'SIZEMIN', 'SIZEMID']

keys_cif = {'_cell_length_a':'CELLA', '_cell_length_b':'CELLB', '_cell_length_c':'CELLC', '_cell_angle_alpha':'ALPHA',
    '_cell_angle_beta':'BETA', '_cell_angle_gamma':'GAMMA', '_cell_volume':'VOLUME', '_cell_formula_units_Z':'ZERR',
    '_exptl_crystal_density_diffrn':'DENSITY', '_exptl_crystal_size_max':'SIZEMAX', '_exptl_crystal_size_mid':'SIZEMID',
    '_exptl_crystal_size_min':'SIZEMIN', '_exptl_absorpt_coefficient_mu':'MU', '_exptl_absorpt_correction_type':'ABSCORR',
    '_exptl_absorpt_correction_T_min':'TMIN','_exptl_absorpt_correction_T_max':'TMAX', '_diffrn_reflns_theta_min':'THETAMIN',
    '_diffrn_reflns_theta_max':'THETAMAX', '_diffrn_reflns_number':'COLLRFL', '_reflns_number_total':'UNIQUE',
    '_reflns_number_gt':'SOMETHING', '_diffrn_measured_fraction_theta_max':'COMPLETENESS', '_chemical_formula_sum':'SUM',
    '_chemical_formula_moiety':'MOI','_space_group_crystal_system':'CRYSSYSTEM','_chemical_formula_weight':'WEIGHT',
    '_refine_ls_number_reflns':'DATA','_refine_ls_number_parameters':'PARAM', '_refine_ls_number_restraints':'RESTR',
    '_refine_ls_restrained_S_all':'GOOF','_refine_ls_R_factor_all':'R1ALL', '_refine_ls_R_factor_gt':'R12SIG',
    '_refine_ls_wR_factor_ref':'WR2ALL', '_refine_ls_wR_factor_gt': 'WR2SIG',
    '_refine_diff_density_max':'HIGHPEAK', '_refine_diff_density_min':'DEEPHOLE', '_space_group_IT_number':'SPGRP'}

indent = ['ALPHA', 'BETA', 'GAMMA', 'R1ALL', 'R12SIG', 'WR2ALL', 'WR2SIG']
rValues = []

def cifReader(cifFile):
    file = open(cifFile,'r').readlines()
    outDict = {}
    outDict['DATE'] = now.strftime("%d.%m.%Y")
    outDict['IDCODE'] = cifFile.split('_')[0]
    for line in file:
        try:
            tempKey = line.split()[0]
            if tempKey in keys_cif.keys():
                try:
                    value = ' '.join(line.split()[1:])
                except IndexError:
                    value = '-'
                outDict[keys_cif[tempKey]] = value
                #print(tempKey,value)
        except IndexError:
            pass
    return outDict

try:
    spinner = Halo(text='Please be patient. I am generating your report.',spinner='smiley', color='red')
    spinner.start()
except:
    pass

args = parser.parse_args()
template = Document(args.docx)
replacements = cifReader(args.input)
#print(replacements.keys())
replacements['USER'] = args.user

if args.special:
    replacements['SPECIAL'] = args.special
else:
    replacements['SPECIAL'] = 'none'

replacements['SIZE'] = '{} x {} x {}'.format(replacements['SIZEMIN'],replacements['SIZEMID'],replacements['SIZEMAX'])

for paragraph in template.paragraphs:
    tabStops = paragraph.paragraph_format.tab_stops
    tabStops.add_tab_stop(Cm(1.0))
    tabStops.add_tab_stop(Cm(4.0))
    tabStops.add_tab_stop(Cm(8.0))
    tabStops.add_tab_stop(Cm(12.0)) 
    for key in replacements.keys():     
 #       print(key)
        if key == 'SOMETHING':
            if key in i.text:
                print(i.text)
        inline = paragraph.runs
        for i in inline:
            if key in i.text:
#                print(key)
#                print(i.text)    
                if key == 'SPGRP':
                    newLine = i.text.replace('SPGRP', '')
                    i.text = newLine
                    transform = etree.XSLT(xslt)
                    new_dom = transform(etree.fromstring(spgrps[replacements[key]]))
                    paragraph._element.append(new_dom.getroot())
                else:
                    newLine = i.text.replace(key, replacements[key])
                    i.text = newLine
                
                
template.save('out.docx')

try:
    spinner.stop()
    spinner.succeed('Report generated')
except:
    pass
